### ISSUE TITLE
cannot compile 

### ISSUE THREAD

**Issue by prr123** [lotusdblabs/lotusdb#106]
go build lotusTest.go
# github.com/flower-corp/lotusdb/index
../../../pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:114:14: assignment mismatch: 2 variables but bucket.Put returns 1 value
../../../pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:147:22: assignment mismatch: 2 variables but bucket.Put returns 1 value
../../../pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:185:22: assignment mismatch: 2 variables but bucket.Delete returns 1 value
../../../pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:205:13: assignment mismatch: 2 variables but tx.Bucket(b.opts.BucketName).Delete returns 1 value
[lotusTest.txt](https://github.com/lotusdblabs/lotusdb/files/12430258/lotusTest.txt)

I think the issue is fixed in the current repository, but release 1.0 has an issue

**Comment by roseduan** [comment]
Yes, I recommend you to use 2.0, which will be released in the near future.
