### ISSUE TITLE
这里内存不应该Put回去

### ISSUE THREAD

**Issue by shaovie** [lotusdblabs/lotusdb#121]
https://github.com/lotusdblabs/lotusdb/blob/dc886e865defbf6f0631e6308836768a8357248b/hashtable.go#L97C9-L97C20
我跟踪了一下 rosedblabs/diskhash: https://github.com/rosedblabs/diskhash/blob/main/bucket.go#L98
https://github.com/rosedblabs/diskhash/blob/2d051ecdb9a5581cb03eeb2078e61384a7ab96da/bucket.go#L112
这里直接将slot保存起来了
所以不能Put回去，而且也没必要使用pool，没意义

**Comment by shaovie** [comment]
而且 bytesBuffer.Put(&encPos) 应该改为 bytesBuffer.Put(encPos)

**Comment by roseduan** [comment]
diskhash 目前不支持的，会在下一个版本发布

**Comment by shaovie** [comment]
但是代码确实有bug

> diskhash 目前不支持的，会在下一个版本发布

**Comment by akiozihao** [comment]
Fixed in #122
