### ISSUE TITLE
Use as a cache on disk

### ISSUE THREAD

**Issue by anacrolix** [lotusdblabs/lotusdb#124]
I've been looking for a cache implementation that stores on disk. I've not found one, but determined that LSMs do not seem to be suitable, but B+Trees usually have performance issues with write. Is your hybrid B+Tree and LSM approach feasible for this problem? In particular it must be possible to keep the total disk storage in use below a certain threshold (maybe exempting the WALs from this requirement), and add some kind of eviction policy (for example LRU or LFU) (this is usually not feasible with pure LSM).

**Comment by roseduan** [comment]
Maybe our project is not suitable for cache, it is an on-disk storage engine instead.
And they(bbolt, badger, lotusdb) do not usually have the cache policy, I think you can investigate  some cache library like groupcache, bigcache, gocache, etc.

**Comment by anacrolix** [comment]
I mean is it suitable for me to implement an eviction policy on top of this implementation. Thank you for your suggestions!

**Comment by anacrolix** [comment]
😿
