### ISSUE TITLE
Is there a benchmark?

### ISSUE THREAD

**Issue by naaive** [lotusdblabs/lotusdb#33]

**Comment by roseduan** [comment]
Not yet, which project do you want to compare with lotusdb? We can do the simple benchmark as soon.

**Comment by naaive** [comment]
rocksdb is preferred

**Comment by baryluk** [comment]
Just learned about `lotusdb`. Would be nice to compare write (with proper durability guarantees) performance (single-core throughput and latency, and write scalability with more thread / goroutines) to `badger`, which has a really good SSI implementation, allowing concurrent readers and (multiple) writers.

Read-heavy dbs are not interesting for me, as there is many fast ones, and it is easy to scale reads.

**Comment by leeson1995** [comment]
> 刚刚了解到`lotusdb`。将写入（具有适当的持久性保证）性能（单核吞吐量和延迟，以及具有更多线程/goroutines 的写入可扩展性）与`badger`具有非常好的 SSI 实现，允许并发读取器和（多个）写入器进行比较会很好。
> 
> 重读 dbs 对我来说并不有趣，因为有很多快速的，而且很容易扩展读取。

+1

**Comment by leeson1995** [comment]
> 袁岩sdb

+1

**Comment by roseduan** [comment]
I will rebuild the whole project and do more changes, please follow me the V2 version.
Thanks for your support!
