### ISSUE TITLE
Refactor: Memtable

### ISSUE THREAD

**Issue by roseduan** [lotusdblabs/lotusdb#58]
1. use wal as the Write Ahead Log https://github.com/rosedblabs/wal
2. use badger skiplist as memory data structure
3. baisc put/get function of memtable
4. flush memtable

**Comment by yanxiaoqi932** [comment]
OK, I will participate in this part, in addition，are there some requirements for part flush memtable?

**Comment by roseduan** [comment]
Thank you all, this is done!
