### ISSUE TITLE
Refactor: Index

### ISSUE THREAD

**Issue by roseduan** [lotusdblabs/lotusdb#59]
1. use bbolt project as backend https://github.com/etcd-io/bbolt
2. basic Open/Get/Put function
3. implement the index interface
4. use bbolt Batch operation to support Put/Delete batch(flush memtable will use it)

**Comment by lts8989** [comment]
I will participate in this part.

**Comment by akiozihao** [comment]
+1

**Comment by adieUkid** [comment]
I want to participate in this part.

**Comment by extravert** [comment]
冲

**Comment by wzlove** [comment]
+1

**Comment by roseduan** [comment]
Thank you all, this is done!
