### ISSUE TITLE
Refactor: Value Log

### ISSUE THREAD

**Issue by roseduan** [lotusdblabs/lotusdb#60]
1. use wal as backend https://github.com/rosedblabs/wal
2. basic Open/Write/Read function
3. Compaction
   * Aims to reclaim all database directory disk space
   * Maybe a little complicated

**Comment by wnz27** [comment]
I want to participate in this part, and do we need a docs folder for add some doc with research literature?

**Comment by chinazmc** [comment]
I want to participate in this part too!!!

**Comment by rickif** [comment]
I'm interested in this part. It's exciting.

**Comment by Sakkana** [comment]
I would like to have a try.

**Comment by roseduan** [comment]
Thank you all, this is done!
