### ISSUE TITLE
Release 2.0.0 Plan: Testing lotusdb performance in benchmark

### ISSUE THREAD

**Issue by yanxiaoqi932** [lotusdblabs/lotusdb#97]
Testint lotusdb performance in benchmark，you can compare performance of lotusdb with other kv engines, such as boltdb, badgerdb, pebble, goleveldb and so on.

**Comment by akiozihao** [comment]
I have done that before [https://github.com/akiozihao/pogreb-bench](https://github.com/akiozihao/pogreb-bench)

**Comment by roseduan** [comment]
> I have done that before https://github.com/akiozihao/pogreb-bench

Right, I have added this in https://github.com/rosedblabs/kvstore-bench, I will update the repo later.
